### ISSUE TITLE
I'm looking for a benchmark for KVS with RESTful API

### ISSUE THREAD

**Issue by zhichao-cao** [shivam-maharshi/YCSB4WebServices#1]
Hi Shivam,

I'm looking for a key-value store benchmark which supports the RESTful API to evaluate the KVS. It seems that you improved the YCSB to benchmark the web service. Is there any instruction docs that I can use to do the evaluation(for example, testing the Openstack Swift)?

Thanks,

Zhichao

**Comment by shivam-maharshi** [comment]
Hi Zhichao-cao,

How urgently do you need this? My rest-binding module is under review by the YCSB team which will get released very soon. It contains a detailed readme which has all the instructions to run. I think that is exactly what you need.

Best,
Shivam

**Comment by zhichao-cao** [comment]
Hi Shivam.

Thanks for the response. I'm working on the test plan and may start the evaluation next week. I have about 1 month time window to test the sample product. I think your work is the benchmark I need exactly. Do you know when are they going to release it?

Cheers,

Zhichao

**Comment by shivam-maharshi** [comment]
Hi Zhichao,

I have some PR reviews to address. I will resolve them today and notify the moderators of YCSB again. I am hopeful that it will be accepted within this week since the PR is in the last stages of review and changes are very minor. I will keep you posted. Meanwhile, here is the link of the PR to keep yourself updated: https://github.com/brianfrankcooper/YCSB/pull/756

Best,
Shivam

**Comment by zhichao-cao** [comment]
Hi Shivam,

Hope the PR review goes well. Keep in touch.

Cheers,
Zhichao

**Comment by shivam-maharshi** [comment]
@zhichao-cao The rest-binding module has been accepted in the official YCSB release. You can take a look at the project here: https://github.com/brianfrankcooper/YCSB/tree/master/rest. There is a detailed README.md with it, feel free to reach out to me for any questions. Happy benchmarking 😄
